name: CMake

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: >-
        sudo apt-get install
        libqt5test5
        libqt5widgets5
        ninja-build
        openbox
        pyqt5-dev
        python3-pyqt5
        qtbase5-dev
        xvfb

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: >-
        cmake $GITHUB_WORKSPACE
        -G Ninja
        -DCMAKE_BUILD_TYPE=$BUILD_TYPE
        -DBUILD_TESTS=TRUE
        -DBUILD_EXAMPLE=TRUE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      env:
        DISPLAY: ":99"
      run: |
        set -ex

        # Start X11 and window manager.
        Xvfb $DISPLAY -screen 0 800x600x24 & sleep 5
        openbox & sleep 8

        ctest -C $BUILD_TYPE

    - name: Build Python Library
      working-directory: ${{github.workspace}}/python
      shell: bash
      env:
        LIBRARY_PATH: ${{runner.workspace}}/build
      run: ./build.sh

    - name: Test Python Library
      working-directory: ${{github.workspace}}/python
      shell: bash
      env:
        DISPLAY: ":99"
        LD_LIBRARY_PATH: ${{runner.workspace}}/build
        PYTHONPATH: ${{github.workspace}}/python/build
        FAKEVIM_CMD: ":q"
      run: |
        set -ex

        # Start X11 and window manager.
        Xvfb $DISPLAY -screen 0 800x600x24 & sleep 5
        openbox & sleep 8

        python test.py
